export const ACHIEVEMENTS = [
  {
    key: "first_lesson",
    title: "Первый шаг",
    description: "Заверши первый урок",
    type: "completed_lessons",
    target: 1,
    xpReward: 5,
    image: "/images/achievements/first-lesson.png",
  },
  {
    key: "five_lessons",
    title: "Уверенный старт",
    description: "Заверши 5 уроков",
    type: "completed_lessons",
    target: 5,
    xpReward: 10,
    image: "/images/achievements/five-lessons.png",
  },
  {
    key: "hundred_xp",
    title: "Сотня опыта",
    description: "Набери 100 XP",
    type: "xp",
    target: 100,
    xpReward: 10,
    image: "/images/achievements/hundred-xp.png",
  },
  {
    key: "three_day_streak",
    title: "Три дня подряд",
    description: "Поддерживай серию 3 дня",
    type: "streak",
    target: 3,
    xpReward: 10,
    image: "/images/achievements/three-day-streak.png",
  },
  {
    key: "ten_correct",
    title: "Точный ученик",
    description: "Дай 10 правильных ответов",
    type: "correct_answers",
    target: 10,
    xpReward: 5,
    image: "/images/achievements/ten-correct.png",
  },
  {
    key: "fifty_correct",
    title: "Знаток",
    description: "Дай 50 правильных ответов",
    type: "correct_answers",
    target: 50,
    xpReward: 15,
    image: "/images/achievements/fifty-correct.png",
  },
];
